# dependencies.R
library(shiny)
library(shinyjs)
library(terra)
library(lubridate)
library(tmap)
library(future)
library(promises)
library(aws.s3)
library(shinydashboard)
library(leaflet)
library(sf)
library(gridExtra)
library(ggplot2)
library(mapview)
